
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import project.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mirela
 */
public class Checkin extends javax.swing.JFrame {

    
    public Checkin() {
        
        initComponents();
        jTextFieldData.setEditable(false);
        jTextFieldPreco.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        jTextFieldData.setText(myFormat.format(cal.getTime()));
    }
    
    String cama;
    String tipoQuarto;
    String numQuarto;
    String numPessoa;
    String preco;
    
    public void detalhesQuarto()
    {
        jComboBoxNumQuarto.removeAllItems();
        jTextFieldPreco.setText("");
        cama=(String)jComboBoxCama.getSelectedItem();
        tipoQuarto=(String)jComboBoxTipoQuarto.getSelectedItem();
        numPessoa=(String)jComboBoxNumPessoa.getSelectedItem();
        
        try
        {
            ResultSet rs = Select.getData("select * from quarto where cama ='"+cama+"' and tipoQuarto='"+tipoQuarto+"' and numPessoa = '"+numPessoa+"' and status = 'Sem reserva'");
            while (rs.next())
            {
                jComboBoxNumQuarto.addItem(rs.getString(1));
            }
            
        } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
       
        String cpf ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fecharBtn = new javax.swing.JButton();
        jLabelCama = new javax.swing.JLabel();
        jLabelTipoQuarto = new javax.swing.JLabel();
        jLabelNumQuarto = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jComboBoxCama = new javax.swing.JComboBox<>();
        jComboBoxTipoQuarto = new javax.swing.JComboBox<>();
        jComboBoxNumQuarto = new javax.swing.JComboBox<>();
        CheckInBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNascimento = new javax.swing.JTextField();
        BuscarBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        LimparBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxNumPessoa = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 110));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-in.png"))); // NOI18N
        jLabel1.setText("Check In de Hóspedes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 42, 340, 49));

        fecharBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });
        getContentPane().add(fecharBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 30, 30));

        jLabelCama.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelCama.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCama.setText("Cama");
        getContentPane().add(jLabelCama, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        jLabelTipoQuarto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTipoQuarto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoQuarto.setText("Tipo do Quarto");
        getContentPane().add(jLabelTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jLabelNumQuarto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelNumQuarto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumQuarto.setText("Número do Quarto");
        getContentPane().add(jLabelNumQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLabelPreco.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreco.setText("Preço");
        getContentPane().add(jLabelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        jTextFieldPreco.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 330, -1));

        jComboBoxCama.setBackground(new java.awt.Color(239, 239, 239));
        jComboBoxCama.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casal", "2 camas solteiro", "2 camas solteiro e 1 cama de casal" }));
        jComboBoxCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCamaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCama, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 330, -1));

        jComboBoxTipoQuarto.setBackground(new java.awt.Color(239, 239, 239));
        jComboBoxTipoQuarto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fumante", "Não-fumante" }));
        jComboBoxTipoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 330, -1));

        jComboBoxNumQuarto.setBackground(new java.awt.Color(239, 239, 239));
        jComboBoxNumQuarto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxNumQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNumQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 330, -1));

        CheckInBtn.setBackground(new java.awt.Color(204, 204, 204));
        CheckInBtn.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        CheckInBtn.setText("Check In");
        CheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CheckInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 170, 59));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guests.png"))); // NOI18N
        jLabel2.setText("Dados do Hóspede");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-chain.png"))); // NOI18N
        jLabel3.setText("Quarto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 167, -1, -1));

        jTextFieldCPF.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 198, 391, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 233, -1, -1));

        jTextFieldNome.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 260, 391, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 297, -1, -1));

        jTextFieldEndereco.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 324, 391, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 361, -1, -1));

        jTextFieldTel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 388, 391, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 424, -1, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 451, 391, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data de Nascimento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 492, -1, -1));

        jTextFieldNascimento.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 526, 391, -1));

        BuscarBtn.setBackground(new java.awt.Color(204, 204, 204));
        BuscarBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Check-In (Hoje)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, -1));

        jTextFieldData.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 330, -1));

        LimparBtn.setBackground(new java.awt.Color(204, 204, 204));
        LimparBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        LimparBtn.setText("Limpar");
        LimparBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LimparBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 90, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantidade de Pessoas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jComboBoxNumPessoa.setBackground(new java.awt.Color(239, 239, 239));
        jComboBoxNumPessoa.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxNumPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBoxNumPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumPessoaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNumPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 330, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basicbg.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        setVisible(false);        
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void LimparBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparBtnActionPerformed
     setVisible(false);
     new Checkin().setVisible(true);
     
    }//GEN-LAST:event_LimparBtnActionPerformed

    private void jComboBoxCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCamaActionPerformed
        detalhesQuarto();
        
    }//GEN-LAST:event_jComboBoxCamaActionPerformed

    private void jComboBoxTipoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoQuartoActionPerformed
        detalhesQuarto();
        
    }//GEN-LAST:event_jComboBoxTipoQuartoActionPerformed

    private void jComboBoxNumPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumPessoaActionPerformed
       detalhesQuarto();     
        
    }//GEN-LAST:event_jComboBoxNumPessoaActionPerformed

    private void jComboBoxNumQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumQuartoActionPerformed
    
        numQuarto=(String)jComboBoxNumQuarto.getSelectedItem();
        try
        {
            ResultSet rs= Select.getData("select * from quarto where numQuarto = '"+numQuarto+"'");
            while (rs.next())
            {
                jTextFieldPreco.setText(rs.getString(5));
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jComboBoxNumQuartoActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
       int check=0;
       cpf=jTextFieldCPF.getText();
       
       if(cpf.equals(""))
       {
           check=1;
           JOptionPane.showMessageDialog(null,"Necessário inserir o CPF");
       }
       else
       {
           ResultSet rs= Select.getData("select * from hospedes where cpfHospede= '"+cpf+"'");
           try
           {
               if (rs.next())
               {
                   check=1;
                   jTextFieldNome.setEditable(false);
                   jTextFieldEndereco.setEditable(false);
                   jTextFieldTel.setEditable(false);
                   jTextFieldEmail.setEditable(false);
                   jTextFieldNascimento.setEditable(false);
                   jTextFieldCPF.setEditable(false);
                   
                   jTextFieldNome.setText(rs.getString(1));
                   jTextFieldEndereco.setText(rs.getString(2));
                   jTextFieldTel.setText(rs.getString(3));
                   jTextFieldEmail.setText(rs.getString(5));
                   jTextFieldNascimento.setText(rs.getString(6));
                   
               }
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null, e);
           }
       }
       if (check == 0)
           JOptionPane.showMessageDialog(null,"CPF está incorreto");
       
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void CheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInBtnActionPerformed
       
        
        String cpfHospede= jTextFieldCPF.getText();
        String nomeHospede= jTextFieldNome.getText();
        String enderecoHospede= jTextFieldEndereco.getText();
        String telHospede= jTextFieldTel.getText();
        String emailHospede= jTextFieldEmail.getText();
        String nascimentoHospede = jTextFieldNascimento.getText();
        String cama= (String)jComboBoxCama.getSelectedItem();
        String tipoQuarto= (String)jComboBoxTipoQuarto.getSelectedItem();
        String numPessoa=(String)jComboBoxNumPessoa.getSelectedItem();
        String numQuarto= (String)jComboBoxNumQuarto.getSelectedItem();
        String preco= jTextFieldPreco.getText();
        String checkin = jTextFieldData.getText();
        String Query = "select max(id) from hospedes";
       
        try
        {
         
            
            if(!preco.equals(""))
            
            {
                Query = "update quarto set status = 'Reservado' where numQuarto ='"+numQuarto+"'";
                InsertUpdateDelete.setData(Query,"");
                
                Query = "update hospedes set status = 'Hospedado' where cpfHospede ='"+cpfHospede+"'";
                InsertUpdateDelete.setData(Query,"");
                
                Query= "insert into checkin (nomeHospede,enderecoHospede,telHospede,cpfHospede,emailHospede,nascimentoHospede,numQuarto,tipoQuarto,cama,numPessoa,preco,dataCheckin) values ('"+nomeHospede+"','"+enderecoHospede+"','"+telHospede+"','"+cpfHospede+"','"+emailHospede+"','"+nascimentoHospede+"','"+numQuarto+"','"+tipoQuarto+"','"+cama+"','"+numPessoa+"','"+preco+"','"+checkin+"')";
                InsertUpdateDelete.setData(Query,"Check In concluído!");
                setVisible(false);
                new Checkin().setVisible(true);
            }
            
        }
        
        catch (Exception e)
        {
        
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
    }//GEN-LAST:event_CheckInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JButton CheckInBtn;
    private javax.swing.JButton LimparBtn;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JComboBox<String> jComboBoxCama;
    private javax.swing.JComboBox<String> jComboBoxNumPessoa;
    private javax.swing.JComboBox<String> jComboBoxNumQuarto;
    private javax.swing.JComboBox<String> jComboBoxTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCama;
    private javax.swing.JLabel jLabelNumQuarto;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTipoQuarto;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNascimento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
