import project.*;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
       
/**
 *
 * @author mirela
 */
public class quartos extends javax.swing.JFrame {
    
    //getters
    public JButton getaddQuartoBtn()
    {
        return addQuartoBtn;
    }
    
    public JTextField getjJTextNumQuarto()
    {
        return jTextNumQuarto;
    }

    public JComboBox<String> getJComboTipoQuarto(){
        return jComboTipoQuarto;
    }

    /**
     * Creates new form quartos
     */
    public quartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fecharBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextNumQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboTipoQuarto = new javax.swing.JComboBox<>();
        jComboCama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addQuartoBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboNumPessoa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(70, 120));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-chain.png"))); // NOI18N
        jLabel1.setText("Gerenciar Quartos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 250, 47));

        fecharBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });
        getContentPane().add(fecharBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 30, 30));

        jTable1.setBackground(new java.awt.Color(239, 239, 239));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do Quarto", "Tipo do Quarto", "Camas", "N. de Pessoas", "Preço", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 590, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número do Quarto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        jTextNumQuarto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextNumQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 310, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo do Quarto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 217, -1, -1));

        jComboTipoQuarto.setBackground(new java.awt.Color(239, 239, 239));
        jComboTipoQuarto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fumante", "Não-fumante" }));
        jComboTipoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 320, -1));

        jComboCama.setBackground(new java.awt.Color(239, 239, 239));
        jComboCama.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casal", "2 camas solteiro", "2 camas solteiro e 1 cama de casal" }));
        getContentPane().add(jComboCama, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 320, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        jTextPreco.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        getContentPane().add(jTextPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 310, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Camas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, -1));

        addQuartoBtn.setBackground(new java.awt.Color(204, 204, 204));
        addQuartoBtn.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        addQuartoBtn.setText("Adicionar Quarto");
        addQuartoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuartoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addQuartoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 180, 50));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Número de pessoas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        jComboNumPessoa.setBackground(new java.awt.Color(239, 239, 239));
        jComboNumPessoa.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboNumPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(jComboNumPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 317, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basicbg.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 670));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
    setVisible(false);
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void addQuartoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuartoBtnActionPerformed
     String numQuarto=jTextNumQuarto.getText();
     String tipoQuarto = (String)jComboTipoQuarto.getSelectedItem();
     String cama = (String)jComboCama.getSelectedItem();
     String numPessoa=(String)jComboNumPessoa.getSelectedItem();
     String preco=jTextPreco.getText();
     
     try{
         
        ResultSet rs = Select.getData("select * from quarto where numQuarto = '"+numQuarto+"'");
        
        if (rs.next()){
             JOptionPane.showMessageDialog(null,"Quarto com esse número já existe no sistema." );
        }
        else
        {
 
        String Query= "insert into quarto values ('"+numQuarto+"','"+tipoQuarto+"','"+cama+"','"+numPessoa+"','"+preco+"','Sem reserva')";
        InsertUpdateDelete.setData(Query,"Atualizado com sucesso");
        setVisible(false);
        new quartos().setVisible(true);
        }
                }
         catch (Exception e)
        { 
        JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_addQuartoBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    ResultSet rs = Select.getData("select * from quarto");
    DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
    try
    {
        while(rs.next())
            
        {
            model.addRow(new Object[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5), rs.getString(6)});
        }
        rs.close();
    }
    catch (Exception e)
    { 
        JOptionPane.showMessageDialog(null, e);
    }
            
    }//GEN-LAST:event_formComponentShown

    private void jComboTipoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quartos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuartoBtn;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JComboBox<String> jComboCama;
    private javax.swing.JComboBox<String> jComboNumPessoa;
    private javax.swing.JComboBox<String> jComboTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextNumQuarto;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
